### ISSUE TITLE
Guides on using different persistent storage: PostgreSQL

### ISSUE THREAD

**Issue by makmakulet** [jas34/scheduledwf#26]
I am exploring the possibility of having [scheduledwf](https://github.com/jas34/scheduledwf) integrated with our Conductor build as a module. And we use PostgreSQL as the main persistence engine for Conductor, do you have any guide / docs that can help  with the proper setup / configuration and build?

Thank you

**Comment by jas34** [comment]
@makmakulet thanks for reaching out to us. We are glad to see that you are interested in using scheduledwf as a module. We will for sure help you out in achieving the same.

At the moment we have [README.md#persistence-layer](https://github.com/jas34/scheduledwf#persistence-layer), which can be followed to write PostgreSQL specific implementation for the following interfaces:
1. ScheduledWfMetadataDAO
2. ScheduledWfExecutionDAO
3. IndexScheduledWfDAO

Once written then these implementations can be injected via guice for Version 1.2.2(like [MySQLPersistenceModule.java](https://github.com/jas34/scheduledwf/blob/v1.2.2/scheduled-mysql-persistence/src/main/java/io/github/jas34/scheduledwf/config/MySQLPersistenceModule.java) and [ScheduledWfServerModule.java](https://github.com/jas34/scheduledwf/blob/v1.2.2/scheduledwf-module/src/main/java/io/github/jas34/scheduledwf/config/ScheduledWfServerModule.java#L32)) or Spring bean for Version 2.0.0(like [MySQLPersistenceConfiguration.java](https://github.com/jas34/scheduledwf/blob/v2.0.0/scheduled-mysql-persistence/src/main/java/io/github/jas34/scheduledwf/config/MySQLPersistenceConfiguration.java)). We also have a plan to extend the same in our new release (likely to be available in a month or two). If you are already planning to do the same then we will be happy to accept PR for the same.

Feel free to share if any other thoughts in mind.

**Comment by jas34** [comment]
We are in the development of introducing PostgreSQL. Refer - #32

**Comment by jas34** [comment]
Closing due to no response from the reporter.
